### PR TITLE
Durhaps this is better

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

replaces the component with ``/Entered()`` ``/Exited()``. Instead of looping through its contents it just holds a reference.
If an item is removed, it will check for another item of that type to use instead. Can only have one overlay per tool.

## Why It's Good For The Game

i really REALLY dont like how it is currently and i especially do not like how it is put on a component.

### CODE REVIEW

**Comment by CoiledLamb** [comment]
image
unfortunately this doesn't preserve one of the functionalities i really wanted from the existing system, that being that the higher tier tools always override lower tier tools. as you can see here it is not defaulting to alien where necessary.

i think if it did that i would merge this, as the component is kind of an artifact from when carts where split between structure and item... since they're both items now there is a good reason for the component to be directly on the object. =

**Comment by JohnFulpWillard** [comment]
> unfortunately this doesn't preserve one of the functionalities i really wanted from the existing system, that being that the higher tier tools always override lower tier tools. as you can see here it is not defaulting to alien where necessary.

can change that, sure

> i think if it did that i would merge this, as the component is kind of an artifact from when carts where split between structure and item...

it isn't now and i don't think that is a good idea anyway

**Comment by CoiledLamb** [comment]
> can change that, sure

cool! that'd be perfect then. i didn't notice any other weirdness in testing

> it isn't now and i don't think that is a good idea anyway

and yeag i do agree. i'm not too attached to it being a component, it's mainly that it had to be that way for the original iteration to work

**Comment by CoiledLamb** [comment]
or rather it could be directly on the object then but it would be a lot of copypasting, the component was jacquerel's suggestion to cut down on that

**Comment by CoiledLamb** [comment]
kay works perfect now. great work and thank you!

**Pull request merged**
